### PR TITLE
Move some narrative from the data to the story notebook

### PR DESCRIPTION
**Pull request by llewelld**
These are work-in-progress changes that move some of the narrative from the data notebook over to the story notebook.

The aim is to try to give some background for the datacollection, since this is an essential part of the process, so important to include some context for the rest of the story.

I've included some small portions of the code, following the same steps and order as the data notebook. I'm not certain it works to include code here (I like the fact that there's code, but I was hoping the code would be more succinct).

### CODE REVIEW

**Comment by llewelld** [comment]
Rebased on top of the latest changes and ran `story.ipynb` through `jupyter-nbconvert --ClearOutputPreprocessor.enabled=True --to=notebook` to make future updates easier.

There's still work to be done on the cell text, so this remains in draft.

**Comment by llewelld** [comment]
All of the data types are now included, so I'm removing the draft tag.

In order to help make clearer the diff, the first commit clears out the data cells and then applies changes on top. To see the important changes, see the final commit of the PR: https://github.com/KatrionaGoldmann/Eurovision_TDS/pull/27/commits/7dbde89a8d3e5129f42c6a7781564ed1aae50666

I'm not convinced by these changes. They make the story much longer by going through all of the data collection steps. This would be really nice to include in my opinion, *if* it were short enough. But if it's done like this I think it'll just be too long. Maybe there's something useful that can be salvaged from this though?... I'm not sure.

**Comment by yongrenjie** [comment]
I read through this and I don't think it's all that bad. To be honest, the story is already going to be quite long regardless of what we do. So, I feel like a little bit of stuff at the start is not a huge problem (and it's entertaining writing!).

To mitigate the 'length' issue, maybe we could:

1. Link people to the comms blog post at the start (this would filter out the lay people who probably shouldn't be reading the full thing, the assumption being that if you are into data science you probably don't mind the additional length);
2. At the start of the data section, write something like 'you can skip to the next part if you're not interested'?

**Comment by yongrenjie** [comment]
Also, if you don't mind @llewelld, I'm going to push some commits cleaning up some stray text (tenses, duplication, etc.) directly.

I'd have preferred to suggest changes on GitHub, but the web version won't let me 😱

**Review by yongrenjie — APPROVED** [review]

**Comment by llewelld** [comment]
Thanks for your careful review @yongrenjie and for the excellent fixes (is "negotionate" not a real word... then it should be :wink: ). I also really like your two suggestions to link to the blog and 'skip this section'. These are both nice mitigations for the length.

**Comment by llewelld** [comment]
I've added a bit of signposting for the block, and also point out that the data collection parts can be safely skipped (see the latest commit). Thanks for the suggestions @yongrenjie, really good ideas.

**Pull request merged**
